openapi: 3.0.0

info:
  title: API Document
  description: API Document
  version: 1.0.0
  contact:
    name: AppMan
    email: test@appman.co.th

servers:
  - url: /smpilp
    description: localhost

paths:
  /person:
    $ref: "./paths/person.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  securitySchemes:
    $ref: "./securitySchemes.yaml"

security:
  - Bearer:
    - /person